export = Object.freeze({
  WAITING_FOR_PLAYER: "WAITING_FOR_PLAYER",
  ROUND_TIMER_START: "ROUND_TIMER_START",
  LOCK_IN_STATE: "LOCK_IN_STATE",
  CHOOSE_FIRST_TURN: "CHOOSE_TURN",
  GAME_STARTED: "GAME_STARTED",
  GAME_WIN: "GAME_WIN",
});
